name = "your-project-name"
type = "javascript"

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "yarn build"

[env.production]
name = "your-project-name-production"
account_id = "your-account-id"
workers_dev = true
route = ""
zone_id = ""

[env.production.build]
command = "yarn build"
